name: trace
description: Live streaming, video reels and feed
publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  #Default
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.5

  #Images
  flutter_svg: ^2.0.6
  cached_network_image: ^3.2.3
  image_cropper: ^4.0.1
  blur: ^3.1.0
  video_editor: ^3.0.0
  wechat_assets_picker: ^8.7.0
  wechat_camera_picker: ^4.0.0
  flutter_image_compress: ^2.0.3
  mime: ^1.0.4
  preload_page_view: ^0.2.0
  like_button: ^2.0.5
  loading_animation_widget: ^1.2.0+4
  sliding_clipped_nav_bar: ^3.1.0+4
  path_provider: ^2.0.15
  carousel_slider: ^4.2.1
  video_player: ^2.7.0
  flutter_sound: ^9.2.13
  flutter_slider_drawer: ^2.1.3
  flutter_app_version_checker: ^0.3.2
  image_picker: ^1.0.0
  custom_zoom_widget: ^0.0.3
  video_thumbnail: ^0.5.3

  #Backend
  parse_server_sdk_flutter: ^5.1.0


  #Chat Live Streaming And Gifs
  tencent_cloud_av_chat_room: ^0.0.4

  #State management
  provider: ^6.0.5

  #Utilities
  #easy_localization: ^3.0.2
  easy_localization: ^3.0.2
  flutter_native_splash: ^2.3.1
  webview_flutter: ^4.2.1
  url_launcher: ^6.1.11
  universal_platform: ^1.0.0+1
  devicelocale: ^0.6.0
  shared_preferences: ^2.1.1
  url_strategy: ^0.2.0
  permission_handler: ^10.4.5
  share_plus: ^7.0.2
  stop_watch_timer: ^2.0.0
  flutter_windowmanager: ^0.2.0
  fade_shimmer: ^2.2.0
  calendar_date_picker2: ^0.5.2
  country_list_pick: ^1.0.1+6
  circular_menu: ^2.0.1
  flutter_keyboard_visibility: ^5.4.1
  text_scroll: ^0.2.0
  emoji_picker_flutter: ^1.6.0
  flip_card: ^0.7.0
  flutter_animation_progress_bar: ^2.3.1
  flutter_cache_manager: ^3.3.0
  in_app_review: ^2.0.6
  auto_size_text_plus: ^3.0.1
  vibration: ^1.8.1

  sticky_grouped_list: ^3.1.0

  iban: ^1.0.1
  wakelock: ^0.6.2
  whatsapp_unilink: ^2.1.0
  keyboard_attachable: ^2.1.0
  just_audio: ^0.9.34
  helpers: ^1.2.3
  upgrader: ^7.0.1
  flutter_staggered_grid_view: ^0.6.2

  #Story
  advstory: ^0.2.1
  story: ^1.1.0

  #Color Picker
  flex_color_picker: ^3.3.0

  #Text for Stories text
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.1

  #Calls and live streaming
  #agora_rtc_engine: ^6.0.0
  agora_rtc_engine: ^5.3.0 #Dont upgrade it
  agora_rtm: ^1.5.0
  flutter_ringtone_player: ^3.2.0
  #flutter_webrtc: ^0.9.21
  #callkeep: ^0.3.3
  flutter_callkit_incoming: ^1.0.3+3

  #Geo data and phone helper
  country_provider: ^1.0.2
  intl_phone_number_input: ^0.7.3+1
  pin_code_fields: ^7.4.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  location: ^5.0.2+1

  #Animations and icons
  #flutter_icons: ^1.1.0
  #lottie: ^2.3.2
  lottie: ^1.4.2
  svgaplayer_flutter: ^2.2.0

  #Firebase
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  firebase_analytics: ^10.4.2
  firebase_performance: ^0.9.2+2
  firebase_crashlytics: ^3.3.2
  firebase_dynamic_links: ^5.3.2

  #push notifications
  another_flushbar: ^1.12.30

  #Social login
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.3
  sign_in_with_apple: ^4.3.0
  flutter_facebook_auth: ^5.0.11

  #payments:
  purchases_flutter: ^5.6.2

  # fake name
  faker: ^2.1.0

  #Ads
  google_mobile_ads: ^3.0.0
  app_tracking_transparency: ^2.0.4

  #video editing
  uuid: 3.0.7

  #Libraries
  xml: ^6.3.0
  flutter_linkify: ^5.0.2
  marquee: ^2.2.3

  #See more or less Text
  expandable_text: ^2.3.0

  #hashtagable: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/svg/
    - assets/audio/
    - assets/lotties/
    - assets/video/
    - assets/audio/

dependency_overrides:
  package_info_plus: ^4.1.0
  parse_server_sdk: ^4.0.2
  dio: ^5.3.2
  intl: ^0.18.1
  http: ^1.0.0
  win32: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/ic_logo_white.png
  #branding: assets/branding-production.png
  color_dark: "#000000"
  image_dark: assets/images/ic_logo_white.png
  #branding_dark: assets/branding-production.png

  android_12:
    image: assets/images/ic_logo_white.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/ic_logo_white.png
    icon_background_color_dark: "#000000"

  web: false